
---
- name: build project
  hosts: db
  become: yes

  tasks:
    - name: Обновить кэш репозиториев менеджера пакетов APT
      apt:
        update_cache: yes
    - name: install packages
      apt:
        name:
          - git
          - maven
        state: present

    - name: fit clone project
      git:
        repo: https://github.com/ylakl/Boxfuse.git
        dest: /opt/Boxfuse
        force: yes

    - name: build project
      command: mvn clean package
      args:
        chdir: /opt/Boxfuse

    - name: copy war
      fetch:
        src: /opt/Boxfuse/target/hello-1.0.war
        dest: /tmp/hello-1.0.war
        flat: yes

- name: run progect
  hosts: web
  become: yes

  tasks:
    - name: Обновить кэш репозиториев менеджера пакетов APT
      apt:
        update_cache: yes

    - name: build artifacts
      apt:
        name:
          - default-jdk
          - tomcat9
        state: present

    - name: copy war
      copy:
        src: /tmp/hello-1.0.war
        dest: /var/lib/tomcat9/webapps/

    - name: start tomcat
      service:
       name: tomcat9
       state: started



